config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  resources :search
end

app/models/search.rb
class Search < ActiveRecord::Base
  validates :username, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	if params[:username].present?
      username = params[:username]
      @user = Octokit.user(username) rescue ""
    end
    respond_to do |format|
    	format.html
    	format.json { render json: @user }
    end
  end

  def show
  	@user = Octokit.user(params[:id].to_i)
  end

  def edit
    @user = Octokit.user(params[:id].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- <div style="margin: 0px auto;width: 400px;"> -->
  <%= yield %>
  <!-- </div> -->
</body>
</html>

<!-- <stylesheet>  
  div {  margin: 0px auto;
    width:400px;}
</stylesheet> -->

app/views/search/edit.html.haml
%h4
  = @user.as_json

app/views/search/index.html.haml
.div 
  %h3
    Find Any User On Github

  = form_tag search_index_path, method: :get, class: "navbar-form navbar-right" do
    %p.box-idiom
      = text_field_tag :username, params[:username], class: "form-control"
      = submit_tag "Search", class: "btn btn-default"
  - if @user.present?
    %h4.success{:style => 'color: green;'}
      We Found Your Username.
    %p
      Click the below user name to view more
    = link_to "#{@user.login}", search_path(@user.id)
  -else
    - if params[:username] == ""
      %h5.error-msg{:style => 'color: red;'}
        Username Can't Be Blank
    - else
      %h5.error-msg{:style => 'color: red;'}
        Cant Find The Username. Please check spelling & try again.


:css
  .box-idiom{margin-right: 56px;
    width: 322px; }
  /   transition:background 1s ease-in;}
  / .success{color: green}
  .div {margin: 0px auto; width:400px;}

app/views/search/show.html.haml
%h4
  = link_to "JSON VIEW", edit_search_path(@user.id)

%table#table.striped
  %thead
    %tr
      %th
        %h3 Username
      %th
        %h3 ID
      %th
        %h3 Avatar_url
      %th
        %h3 Gravatar_id
      %th
        %h3 URL
      %th
        %h3 html_url
      %th
        %h3 followers_url
      %th
        %h3 following_url
      %th
        %h3 gist_url
      %th
        %h3 starred_url
      %th
        %h3 subscriptions_url
      %th
        %h3 organizations_url
      %th
        %h3 repos_url
      %th
        %h3 events_url
      %th
        %h3 received_events_url
      %th
        %h3 type
      %th
        %h3 site_admin
      %th
        %h3 name
      %th
        %h3 company
      %th
        %h3 blog
      %th
        %h3 location
      %th
        %h3 email
      %th
        %h3 hireable
      %th
        %h3 bio
      %th
        %h3 public_repos
      %th
        %h3 public_gists
      %th
        %h3 followers
      %th
        %h3 following
      %th
        %h3 created_at
      %th
        %h3 updated_at
  %tbody
    %tr
      %td
        %p 
          = @user.login
      %td
        %p 
          = @user.id
      %td
        %p
          = @user.avatar_url
      %td
        %p
          = @user.gravatar_id
      %td
        %p
          = @user.url
      %td
        %p
          = @user.html_url
      %td
        %p
          = @user.followers_url
      %td
        %p
          = @user.following_url
      %td
        %p
          = @user.gists_url
      %td
        %p
          = @user.starred_url
      %td
        %p
          = @user.subscriptions_url
      %td
        %p
          = @user.organizations_url
      %td
        %p
          = @user.repos_url
      %td
        %p
          = @user.events_url
      %td
        %p
          = @user.received_events_url
      %td
        %p
          = @user.type
      %td
        %p
          = @user.site_admin
      %td
        %p
          = @user.name
      %td
        %p
          = @user.company
      %td
        %p
          = @user.blog
      %td
        %p
          = @user.location
      %td
        %p
          = @user.email
      %td
        %p
          = @user.hireable
      %td
        %p
          = @user.bio
      %td
        %p
          = @user.public_repos
      %td
        %p
          = @user.public_gists
      %td
        %p
          = @user.followers
      %td
        %p
          = @user.following
      %td
        %p
          = @user.created_at
      %td
        %p
          = @user.updated_at


:css
  table th {
    background-color: grey;
    color: white;
  }
  table th, table td {
    padding: 5px;
  }
  table th {
    text-align: left;
  }
  table th, table td {
    padding: 5px;
  }
  table th {
    text-align: left;
  }